// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: sandbox.proto

package sandboxproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RunSandboxCompileCodeClient is the client API for RunSandboxCompileCode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunSandboxCompileCodeClient interface {
	RunSandboxCompileCode(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ResponseMessage, error)
}

type runSandboxCompileCodeClient struct {
	cc grpc.ClientConnInterface
}

func NewRunSandboxCompileCodeClient(cc grpc.ClientConnInterface) RunSandboxCompileCodeClient {
	return &runSandboxCompileCodeClient{cc}
}

func (c *runSandboxCompileCodeClient) RunSandboxCompileCode(ctx context.Context, in *RequestMessage, opts ...grpc.CallOption) (*ResponseMessage, error) {
	out := new(ResponseMessage)
	err := c.cc.Invoke(ctx, "/sandbox.RunSandboxCompileCode/RunSandboxCompileCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunSandboxCompileCodeServer is the server API for RunSandboxCompileCode service.
// All implementations must embed UnimplementedRunSandboxCompileCodeServer
// for forward compatibility
type RunSandboxCompileCodeServer interface {
	RunSandboxCompileCode(context.Context, *RequestMessage) (*ResponseMessage, error)
	mustEmbedUnimplementedRunSandboxCompileCodeServer()
}

// UnimplementedRunSandboxCompileCodeServer must be embedded to have forward compatible implementations.
type UnimplementedRunSandboxCompileCodeServer struct {
}

func (UnimplementedRunSandboxCompileCodeServer) RunSandboxCompileCode(context.Context, *RequestMessage) (*ResponseMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunSandboxCompileCode not implemented")
}
func (UnimplementedRunSandboxCompileCodeServer) mustEmbedUnimplementedRunSandboxCompileCodeServer() {}

// UnsafeRunSandboxCompileCodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunSandboxCompileCodeServer will
// result in compilation errors.
type UnsafeRunSandboxCompileCodeServer interface {
	mustEmbedUnimplementedRunSandboxCompileCodeServer()
}

func RegisterRunSandboxCompileCodeServer(s grpc.ServiceRegistrar, srv RunSandboxCompileCodeServer) {
	s.RegisterService(&RunSandboxCompileCode_ServiceDesc, srv)
}

func _RunSandboxCompileCode_RunSandboxCompileCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunSandboxCompileCodeServer).RunSandboxCompileCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sandbox.RunSandboxCompileCode/RunSandboxCompileCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunSandboxCompileCodeServer).RunSandboxCompileCode(ctx, req.(*RequestMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// RunSandboxCompileCode_ServiceDesc is the grpc.ServiceDesc for RunSandboxCompileCode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunSandboxCompileCode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sandbox.RunSandboxCompileCode",
	HandlerType: (*RunSandboxCompileCodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunSandboxCompileCode",
			Handler:    _RunSandboxCompileCode_RunSandboxCompileCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sandbox.proto",
}
